// <auto-generated />
namespace TokenAuth.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class add_model_user_clientdetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_model_user_clientdetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202407071647070_add_model_user_clientdetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
